pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            image: mcr.microsoft.com/dotnet/core/sdk:3.1
            script:
              - cd UnitTest
              - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
              - dotnet restore
              - dotnet build --no-restore --configuration Release
              - dotnet test --no-build --configuration Release
              - cd ../DatingApp
              - dotnet restore
              - dotnet build --no-restore --configuration Release
        - step:
            name: Build and Test
            image: node:10.15.3
            script:
              - cd DatingAppCS
              - npm install
              - npm run build
        - step:
            name: Docker
            image: mcr.microsoft.com/dotnet/core/sdk:3.1
            script:
              - docker build -t aspnetapp .
              - docker run -d -p 8080:80 --name DatingApp aspnetapp
            
