#  Template NodeJS build
#  Template .NET Core build
#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

#  This template allows you to validate your .NET Core package.
#  The workflow allows running tests and code linting on the default branch.

image: mcr.microsoft.com/dotnet/core/sdk:3.1

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test API
            caches:
              - dotnetcore
            script:
              - cd UnitTest
              - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
              - dotnet restore
              - dotnet build --no-restore --configuration Release
              - dotnet test --no-build --configuration Release
              - cd ../DatingApp
              - dotnet restore
              - dotnet build --no-restore --configuration Release
         - step:
             image: node:10.15.3
             name: Build and Test Client Side
             caches:
              - node
             script:
              - cd DatingAppCS
              - ng build
              - npm test