version: "3"
services:
  say-hello:
    image: krooter/datingapp:latest
    network_mode: bridge
    container_name: datingapp
    expose:
      - 5000
    ports:
      - 5000:5000
    restart: unless-stopped